package com.www.demo.model.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * @description 角色菜单表
 * @version 1.0
 * @author www
 * @date 2021/7/18 19:18
 */
public class SysRoleMenu implements Serializable {
    /**
     * Database Column Remarks:
     *   菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.SRM_ID
     *
     * @mbg.generated
     */
    private Integer srmId;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.ROLE_ID
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * Database Column Remarks:
     *   父级菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.MENU_ID
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.SYS_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date sysUpdateDate;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.SYS_CREATE_DATE
     *
     * @mbg.generated
     */
    private Date sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.SRM_ID
     *
     * @return the value of sys_role_menu.SRM_ID
     *
     * @mbg.generated
     */
    public Integer getSrmId() {
        return srmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.SRM_ID
     *
     * @param srmId the value for sys_role_menu.SRM_ID
     *
     * @mbg.generated
     */
    public void setSrmId(Integer srmId) {
        this.srmId = srmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.ROLE_ID
     *
     * @return the value of sys_role_menu.ROLE_ID
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.ROLE_ID
     *
     * @param roleId the value for sys_role_menu.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.MENU_ID
     *
     * @return the value of sys_role_menu.MENU_ID
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.MENU_ID
     *
     * @param menuId the value for sys_role_menu.MENU_ID
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.SYS_UPDATE_DATE
     *
     * @return the value of sys_role_menu.SYS_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getSysUpdateDate() {
        return sysUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.SYS_UPDATE_DATE
     *
     * @param sysUpdateDate the value for sys_role_menu.SYS_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setSysUpdateDate(Date sysUpdateDate) {
        this.sysUpdateDate = sysUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.SYS_CREATE_DATE
     *
     * @return the value of sys_role_menu.SYS_CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for sys_role_menu.SYS_CREATE_DATE
     *
     * @mbg.generated
     */
    public void setSysCreateDate(Date sysCreateDate) {
        this.sysCreateDate = sysCreateDate;
    }
}