package com.www.demo.model.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * <p>@Description 菜单表 </p>
 * <p>@Version 1.0 </p>
 * <p>@Author www </p>
 * <p>@Date 2021/8/1 20:56 </p>
 */
public class SysMenuEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_ID
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     * Database Column Remarks:
     *   菜单编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_CODE
     *
     * @mbg.generated
     */
    private String menuCode;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_NAME
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     * Database Column Remarks:
     *   父级菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.PARENT_ID
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   菜单图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_ICON
     *
     * @mbg.generated
     */
    private String menuIcon;

    /**
     * Database Column Remarks:
     *   菜单路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_URL
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     * Database Column Remarks:
     *   菜单序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.ORDER_NUM
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.IS_DELETE
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.SYS_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date sysUpdateDate;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.SYS_CREATE_DATE
     *
     * @mbg.generated
     */
    private Date sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_ID
     *
     * @return the value of sys_menu.MENU_ID
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_ID
     *
     * @param menuId the value for sys_menu.MENU_ID
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_CODE
     *
     * @return the value of sys_menu.MENU_CODE
     *
     * @mbg.generated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_CODE
     *
     * @param menuCode the value for sys_menu.MENU_CODE
     *
     * @mbg.generated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_NAME
     *
     * @return the value of sys_menu.MENU_NAME
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_NAME
     *
     * @param menuName the value for sys_menu.MENU_NAME
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.PARENT_ID
     *
     * @return the value of sys_menu.PARENT_ID
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.PARENT_ID
     *
     * @param parentId the value for sys_menu.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_ICON
     *
     * @return the value of sys_menu.MENU_ICON
     *
     * @mbg.generated
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_ICON
     *
     * @param menuIcon the value for sys_menu.MENU_ICON
     *
     * @mbg.generated
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_URL
     *
     * @return the value of sys_menu.MENU_URL
     *
     * @mbg.generated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_URL
     *
     * @param menuUrl the value for sys_menu.MENU_URL
     *
     * @mbg.generated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.ORDER_NUM
     *
     * @return the value of sys_menu.ORDER_NUM
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.ORDER_NUM
     *
     * @param orderNum the value for sys_menu.ORDER_NUM
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.IS_DELETE
     *
     * @return the value of sys_menu.IS_DELETE
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.IS_DELETE
     *
     * @param isDelete the value for sys_menu.IS_DELETE
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.SYS_UPDATE_DATE
     *
     * @return the value of sys_menu.SYS_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getSysUpdateDate() {
        return sysUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.SYS_UPDATE_DATE
     *
     * @param sysUpdateDate the value for sys_menu.SYS_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setSysUpdateDate(Date sysUpdateDate) {
        this.sysUpdateDate = sysUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.SYS_CREATE_DATE
     *
     * @return the value of sys_menu.SYS_CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for sys_menu.SYS_CREATE_DATE
     *
     * @mbg.generated
     */
    public void setSysCreateDate(Date sysCreateDate) {
        this.sysCreateDate = sysCreateDate;
    }
}